### PR TITLE
Netstandard

### PR DESCRIPTION
**Pull request by jasonchester**
Conversion of the library to netstandard2.0

### CODE REVIEW

**Review by nmpollak — COMMENTED** [review]
@jasonchester Thanks a lot for your contribution, I will review today or tomorrow!

**Review by nmpollak — CHANGES_REQUESTED** [review]
Hi @jasonchester , I was not able to compile the source since the compiler nagged about duplicate "[assembly: AssemblyDescription("")]" in AssemblyInfo.cs (all 4 projects). Simply removing that attribute should do the trick. Rest works like a charm. Thnx Andreas

**Comment by jasonchester** [comment]
@apollak I had added the following block to the .csproj files to prevent similar errors. Removing those attributes is another and maybe even more attractive option but I did not know which one you preferred.

```
<PropertyGroup>
   <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
   <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
   <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
   <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
   <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
   <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
</PropertyGroup>
```

it also looks like there is a single attribute that can be used to turn off all generation. https://compiledexperience.com/blog/posts/assemblyinfo-generation 

```
<PropertyGroup>
   <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
</PropertyGroup>
```

Let me know if you prefer the info maintained in attributes or the .csproj files and I can make that change.

**Comment by apollak** [comment]
@jasonchester Thanks Jason, I would like to store the information in the .csproj files as it seems to be the "new way" (Until MS changes this again :-)). Thanks Andreas

**Comment by jasonchester** [comment]
had to change description to avoid an annoying warning...
see: https://github.com/NuGet/Home/issues/4587

before:
> Extension Library with additional functionality for CosmosDB Graph. Allows Serialization/Deserialization of custom objects for Graph in CosmosDB. Also allows to serialize GraphObjects to native CosmosDB JSON thus allowing you to add Vertices and Edges quickly via normal DocumentDB SQL instead of Gremlin.

after: 
> Serialization/Deserialization for POCO to CosmosDB Graphs. 
> Insert Vertices and Edges with Document DB SQL instead of gremlin.
> Retrieve graph results as custom POCO in-memory graph representations.

**Comment by apollak** [comment]
Thanks a lot @jasonchester , I merged it :-)

**Pull request merged**
